# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-11 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_completedlessonauthorship_completedlessonregex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedlessonauthorship',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='completedlessonregex',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='CompletedLesson',
        ),
        migrations.DeleteModel(
            name='CompletedLessonAuthorship',
        ),
        migrations.DeleteModel(
            name='CompletedLessonRegex',
        ),
    ]
